# Generated by Django 2.2.1 on 2019-08-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesImporter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='language',
            new_name='imdb_id',
        ),
    ]
