# Generated by Django 2.2.1 on 2019-08-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesImporter', '0002_auto_20190824_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
