# Generated by Django 2.2.1 on 2019-08-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesImporter', '0003_auto_20190824_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre_3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
