# Generated by Django 2.2.1 on 2019-05-26 20:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_auto_20190526_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('context', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('recommendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_recieved', to='recommendations.User')),
                ('recommender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_made', to='recommendations.User')),
            ],
        ),
    ]
