# Generated by Django 2.2.1 on 2019-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_trusteduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='context',
            field=models.TextField(null=True),
        ),
    ]
