# Generated by Django 2.2.4 on 2019-09-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesImporter', '0005_enable_fuzzystrmatch'),
        ('recommendations', '0008_auto_20190526_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='moviesImporter.Movie'),
        ),
    ]
