# Generated by Django 2.2.4 on 2019-09-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0009_recommendation_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='moviesImporter.Movie'),
        ),
    ]
